// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Intercept Edge Functions in local demo mode
import { isLocalDemoAuthEnabled } from '@/lib/localDemoAuth';
import { handleLocalFunctionInvoke } from '@/lib/localAIService';

const functionsProto = Object.getPrototypeOf(supabase.functions);
const originalInvoke = functionsProto.invoke;
functionsProto.invoke = async function (functionName: string, options?: any) {
  if (isLocalDemoAuthEnabled()) {
    try {
      const result = await handleLocalFunctionInvoke(functionName, options);
      return { data: result.data || result, error: null };
    } catch (error: any) {
      console.error(`[Local AI Sim Error] for ${functionName}:`, error);
      return { data: null, error };
    }
  }
  return await originalInvoke.apply(this, [functionName, options]);
};